//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cantidadpornumeros
    {
        public int IdArticulo { get; set; }
        public int N36 { get; set; }
        public int N37 { get; set; }
        public int N38 { get; set; }
        public int N39 { get; set; }
        public int N40 { get; set; }
        public int N41 { get; set; }
        public int N42 { get; set; }
        public int N43 { get; set; }
        public int N44 { get; set; }
        public int N45 { get; set; }
        public int N46 { get; set; }
        public int N47 { get; set; }
    
        public virtual articulos articulos { get; set; }
    }
}
