//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class numeroscalzado
    {
        public string CodArticulo { get; set; }
        public int C36 { get; set; }
        public int C37 { get; set; }
        public int C38 { get; set; }
        public int C39 { get; set; }
        public int C40 { get; set; }
        public int C41 { get; set; }
        public int C42 { get; set; }
        public int C43 { get; set; }
        public int C44 { get; set; }
        public int C45 { get; set; }
        public int C46 { get; set; }
        public int C47 { get; set; }
        public int TotalCantidadArticulo { get; set; }
    
        public virtual articulos ARTICULO { get; set; }
    }
}
